trigger:
  batch: true
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

steps:
  # On every PR, build the addon and make it available for download as an artifact
  - template: build.yml
    parameters:
      py_versions: [ 'py2', 'py3' ]

  # When triggered by a tag, publish the built addon to the repo server
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
    - template: publish.yml
      parameters:
        py_versions: [ 'py2', 'py3' ]
