name: Publish Jellyfin-Kodi

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update Draft
        uses: release-drafter/release-drafter@v6.1.0
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Build addon
        run: python build.py

      - name: Publish Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          retention-days: 14
          name: py3-build-artifact
          path: |
            *.zip

      - name: Upload to repo server
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -vrptz
          path: '*.zip'
          remote_path: /srv/incoming/kodi
          remote_host: ${{ secrets.REPO_HOST }}
          remote_user: ${{ secrets.REPO_USER }}
          remote_key: ${{ secrets.REPO_KEY }}

      - name: Add to Kodi repo and clean up
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REPO_HOST  }}
          username: ${{ secrets.REPO_USER }}
          key: ${{ secrets.REPO_KEY }}
          script_stop: true
          script: |
            sudo /usr/local/bin/kodirepo add /srv/incoming/kodi/plugin.video.jellyfin+py3.zip --datadir /srv/repository/main/client/kodi/py3
            rm /srv/incoming/kodi/plugin.video.jellyfin+py3.zip
